language: node_js
node_js:
- "0.10"

before_install:
- git config --global url."https://".insteadOf git://  # travis doesn't like touching git so this is a workaround

install:
- npm install
- ./node_modules/.bin/bower install

before_script:
- nohup ./node_modules/.bin/gulp beforetest &
- sleep 5

script: phantomjs phantomtest.js http://localhost:8000/tests.html  # not npm test cuz travis has phantomjs preinstalled
